let symbols = [
  {
    symbol: "A",
    name: "Agilent Technologies Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1999-11-18",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AA",
    name: "Alcoa Corp",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2016-10-18",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAA",
    name: "AXS FIRST PRIORITY CLO BOND ETF ",
    exchange: "NYSE ARCA",
    assetType: "ETF",
    ipoDate: "2020-09-09",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAAU",
    name: "Goldman Sachs Physical Gold ETF",
    exchange: "BATS",
    assetType: "ETF",
    ipoDate: "2018-08-15",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAC",
    name: "Ares Acquisition Corporation - Class A",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2021-03-25",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAC-U",
    name: "Ares Acquisition Corporation - Units (1 Ord Share Class A & 1/5 War)",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2021-02-02",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAC-WS",
    name: "Ares Acquisition Corporation - Warrants (01/01/9999)",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2021-03-25",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AACG",
    name: "ATA Creativity Global",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2008-01-29",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AACI",
    name: "Armada Acquisition Corp I",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-11-10",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AACIU",
    name: "Armada Acquisition Corp I - Units (1 Ord & 1/2 War)",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-08-13",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AACIW",
    name: "Armada Acquisition Corp I - Warrants (13/08/2026)",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-11-11",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AADI",
    name: "Aadi Bioscience Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2017-08-08",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AADR",
    name: "AdvisorShares Dorsey Wright ADR ETF",
    exchange: "NASDAQ",
    assetType: "ETF",
    ipoDate: "2010-07-21",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAIC",
    name: "Arlington Asset Investment Corp - Class A",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1997-12-23",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAIC-P-B",
    name: "Arlington Asset Investment Corp",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2017-05-16",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAIC-P-C",
    name: "Arlington Asset Investment Corp",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2019-03-06",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAIN",
    name: "Arlington Asset Investment Corp",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2021-07-19",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAL",
    name: "American Airlines Group Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2005-09-27",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAM-P-A",
    name: "Apollo Asset Management Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2022-01-03",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAM-P-B",
    name: "Apollo Asset Management Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2022-01-03",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAMC",
    name: "Altisource Asset Management Corp",
    exchange: "NYSE MKT",
    assetType: "Stock",
    ipoDate: "2012-12-13",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAME",
    name: "Atlantic American Corp",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "1984-09-07",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAN",
    name: "Aarons Company Inc (The)",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2020-11-25",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAN-W",
    name: "Aarons Holdings Company Inc When Issued",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2020-11-25",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAOI",
    name: "Applied Optoelectronics Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2013-09-26",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAON",
    name: "AAON Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "1992-12-16",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAP",
    name: "Advance Auto Parts Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2001-11-29",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAPB",
    name: "GraniteShares 1.75x Long AAPL Daily ETF",
    exchange: "NASDAQ",
    assetType: "ETF",
    ipoDate: "2022-08-09",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAPD",
    name: "Direxion Daily AAPL Bear 1X Shares",
    exchange: "NASDAQ",
    assetType: "ETF",
    ipoDate: "2022-08-09",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAPL",
    name: "Apple Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "1980-12-12",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAPU",
    name: "Direxion Daily AAPL Bull 1.5X Shares",
    exchange: "NASDAQ",
    assetType: "ETF",
    ipoDate: "2022-08-09",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAQC",
    name: "Accelerate Acquisition Corp - Class A",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2021-05-10",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAQC-U",
    name: "Accelerate Acquisition Corp - Units (1 Ord Share Class A & 1/3 War)",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2021-03-18",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAQC-WS",
    name: "Accelerate Acquisition Corp - Warrants (15/03/2028)",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2021-05-10",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAT",
    name: "American Assets Trust Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2011-01-13",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AATC",
    name: "Autoscope Technologies Corporation",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-07-21",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAU",
    name: "Almaden Minerals Ltd",
    exchange: "NYSE MKT",
    assetType: "Stock",
    ipoDate: "2005-12-20",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAWW",
    name: "Atlas Air Worldwide Holdings Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2005-11-09",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AAXJ",
    name: "iShares MSCI All Country Asia ex Japan ETF",
    exchange: "NASDAQ",
    assetType: "ETF",
    ipoDate: "2008-08-15",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "AB",
    name: "AllianceBernstein Holding Lp",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1988-04-15",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABB",
    name: "ABB Ltd",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2001-04-06",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABBV",
    name: "Abbvie Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2013-01-02",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABC",
    name: "Amerisource Bergen Corp",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1995-04-04",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABCB",
    name: "Ameris Bancorp",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "1994-05-19",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABCL",
    name: "AbCellera Biologics Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2020-12-11",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABCM",
    name: "Abcam",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2010-12-03",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABEO",
    name: "Abeona Therapeutics Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "1980-09-19",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABEQ",
    name: "Absolute Select Value ETF",
    exchange: "NYSE ARCA",
    assetType: "ETF",
    ipoDate: "2020-01-22",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABEV",
    name: "Ambev S.A.",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1997-03-05",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABG",
    name: "Asbury Automotive Group Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2002-03-21",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABGI",
    name: "ABG Acquisition Corp I - Class A",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-02-17",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABIO",
    name: "ARCA biopharma Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "1997-08-08",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABM",
    name: "ABM Industries Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1984-07-19",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABMD",
    name: "Abiomed Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "1987-07-30",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABNB",
    name: "Airbnb Inc - Class A",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2020-12-10",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABOS",
    name: "Acumen Pharmaceuticals Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-07-01",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABR",
    name: "Arbor Realty Trust Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2004-04-07",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABR-P-D",
    name: "Arbor Realty Trust Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2021-05-26",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABR-P-E",
    name: "Arbor Realty Trust Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2021-08-05",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABR-P-F",
    name: "Arbor Realty Trust Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2021-10-05",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABSI",
    name: "Absci Corp",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-07-22",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABST",
    name: "Absolute Software Corporation",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2020-10-28",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "ABT",
    name: "Abbott Laboratories",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1983-04-06",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BBSI",
    name: "Barrett Business Services Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "1993-06-14",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BBU",
    name: "Brookfield Business Partners L.P.",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2016-06-17",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BBUC",
    name: "Brookfield Business Corp - Class A - Class A (Sub Voting)",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2022-03-07",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BBUC-W",
    name: "Brookfield Business Corporation Class A Exchangeable Subordinate WhenIssued",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2022-03-04",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BBUS",
    name: "JPMorgan BetaBuilders U.S. Equity ETF",
    exchange: "BATS",
    assetType: "ETF",
    ipoDate: "2019-03-13",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BBVA",
    name: "Banco Bilbao Vizcaya Argentaria.",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1988-12-15",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BBW",
    name: "Build A Bear Workshop Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2004-10-28",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BBWI",
    name: "Bath & Body Works Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1985-07-01",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BBWI-W",
    name: "Bath & Body Works Inc Exdistribution WhenIssued",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2021-07-21",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BBY",
    name: "Best Buy Co. Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1985-04-19",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BC",
    name: "Brunswick Corp",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1981-12-31",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BC-P-A",
    name: "Brunswick Corp",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2018-10-08",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BC-P-B",
    name: "Brunswick Corp",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2018-12-06",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BC-P-C",
    name: "Brunswick Corp",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2019-03-08",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCAB",
    name: "BioAtla Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2020-12-16",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCAN",
    name: "BYND Cannasoft Enterprises Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2022-05-31",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCAT",
    name: "BlackRock Capital Allocation Trust",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2020-09-25",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCBP",
    name: "BCB Bancorp Inc (NJ)",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2003-10-15",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCC",
    name: "Boise Cascade Company",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2013-02-06",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCD",
    name: "abrdn Bloomberg All Comm Longer Dt Strategy K-1 Free ETF",
    exchange: "NYSE ARCA",
    assetType: "ETF",
    ipoDate: "2017-03-31",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCDA",
    name: "BioCardia Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2008-03-14",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCDAW",
    name: "BioCardia Inc - Warrants (26/07/2022)",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2019-08-02",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCDF",
    name: "Horizon Kinetics Blockchain Development ETF",
    exchange: "NYSE ARCA",
    assetType: "ETF",
    ipoDate: "2022-08-02",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCE",
    name: "BCE Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1982-11-15",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCEL",
    name: "Atreca Inc - Class A",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2019-06-20",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCH",
    name: "Banco de Chile",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2002-01-08",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCI",
    name: "abrdn Bloomberg All Commodity Strategy K-1 Free ETF",
    exchange: "NYSE ARCA",
    assetType: "ETF",
    ipoDate: "2017-03-31",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCIM",
    name: "abrdn Bloomberg Industrial Metals Strategy K-1 Free ETF",
    exchange: "NYSE ARCA",
    assetType: "ETF",
    ipoDate: "2021-09-23",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCLI",
    name: "Brainstorm Cell Therapeutics Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2003-08-28",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCM",
    name: "iPath Pure Beta Broad Commodity ETN",
    exchange: "NYSE ARCA",
    assetType: "ETF",
    ipoDate: "2011-04-21",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCML",
    name: "BayCom Corp",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2004-08-09",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCO",
    name: "Brink`s Company",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1996-01-03",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCOR",
    name: "Blucora Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "1998-12-15",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCOV",
    name: "Brightcove Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2012-02-17",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCOW",
    name: "1895 Bancorp of Wisconsin Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2019-01-09",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCPC",
    name: "Balchem Corp",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "1986-06-03",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCRX",
    name: "Biocryst Pharmaceuticals Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "1994-03-04",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCS",
    name: "Barclays plc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1986-09-10",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCSA",
    name: "Blockchain Coinvestors Acquisition Corp I - Class A",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-12-31",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCSAU",
    name: "Blockchain Coinvestors Acquisition Corp I - Units (1 Ord Share Class A & 1/2 War)",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-11-10",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCSAW",
    name: "Blockchain Coinvestors Acquisition Corp I - Warrants (01/09/2026)",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-12-31",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCSF",
    name: "Bain Capital Specialty Finance Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2018-11-15",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCTX",
    name: "BriaCell Therapeutics Corp",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-02-24",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCTXW",
    name: "BriaCell Therapeutics Corp - Warrants (24/02/2025)",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-02-24",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCV",
    name: "Bancroft Fund Ltd",
    exchange: "NYSE MKT",
    assetType: "ETF",
    ipoDate: "1984-09-07",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCV-P-A",
    name: "Bancroft Fund Ltd",
    exchange: "NYSE MKT",
    assetType: "Stock",
    ipoDate: "2016-08-05",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCX",
    name: "BlackRock Resources & Commodities Strategy Trust",
    exchange: "NYSE",
    assetType: "ETF",
    ipoDate: "2011-03-29",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BCYC",
    name: "Bicycle Therapeutics Plc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2019-05-23",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BDC",
    name: "Belden Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1993-11-24",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BDCX",
    name: "UBS AG London Branch",
    exchange: "NYSE ARCA",
    assetType: "Stock",
    ipoDate: "2020-06-03",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BDCZ",
    name: "BDCZ",
    exchange: "NYSE ARCA",
    assetType: "ETF",
    ipoDate: "2015-10-09",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BDEC",
    name: "Innovator U.S. Equity Buffer ETF - December",
    exchange: "BATS",
    assetType: "ETF",
    ipoDate: "2019-12-02",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BDJ",
    name: "BlackRock Enhanced Equity Dividend Trust",
    exchange: "NYSE",
    assetType: "ETF",
    ipoDate: "2005-08-29",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BDL",
    name: "Flanigan`s Enterprises Inc",
    exchange: "NYSE MKT",
    assetType: "Stock",
    ipoDate: "1984-09-07",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BDN",
    name: "Brandywine Realty Trust",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1986-07-24",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BDRY",
    name: "Breakwave Dry Bulk Shipping ETF",
    exchange: "NYSE ARCA",
    assetType: "ETF",
    ipoDate: "2018-03-22",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BDSX",
    name: "Biodesix Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2020-10-28",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BDTX",
    name: "Black Diamond Therapeutics Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2020-01-30",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BDX",
    name: "Becton Dickinson And Company",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1983-04-06",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BDXA",
    name: "Becton Dickinson and Company Depositary Shares each Representing a 120th Interest in a Share of 6125 Mandatory Convertible Preferred Stock Series A 100 par",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2017-05-11",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BDXB",
    name: "Becton Dickinson And Company",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2020-05-21",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BE",
    name: "Bloom Energy Corp - Class A",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2018-07-25",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BEAM",
    name: "Beam Therapeutics Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2020-02-06",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BEAT",
    name: "HeartBeam Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-11-11",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BEATW",
    name: "HeartBeam Inc - Warrants (31/10/2026)",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-11-11",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BECN",
    name: "Beacon Roofing Supply Inc - Class A",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2004-09-23",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BECO",
    name: "BlackRock Future Climate and Sustainable Economy ETF",
    exchange: "NYSE ARCA",
    assetType: "ETF",
    ipoDate: "2021-08-05",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BEDU",
    name: "Bright Scholar Education Holdings Ltd",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2017-05-18",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BEDZ",
    name: "AdvisorShares Hotel ETF",
    exchange: "NYSE ARCA",
    assetType: "ETF",
    ipoDate: "2021-04-21",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BEEM",
    name: "Beam Global",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2010-04-30",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BEEMW",
    name: "Beam Global - Warrants (30/12/2023)",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2019-04-16",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BEKE",
    name: "KE Holdings Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2020-08-13",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BELFA",
    name: "Bel Fuse Inc - Class A",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "1984-09-07",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BELFB",
    name: "Bel Fuse Inc - Class B",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "1998-07-10",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BEN",
    name: "Franklin Resources Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1984-09-07",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BENE",
    name: "Benessere Capital Acquisition Corp - Class A",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-01-28",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BENER",
    name: "Benessere Capital Acquisition Corp",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-01-28",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BENEU",
    name: "Benessere Capital Acquisition Corp - Units (1 Ord Class A 1 Rts & 3/4 War)",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-01-05",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BENEW",
    name: "Benessere Capital Acquisition Corp - Warrants (22/12/2025)",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-01-28",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BEP",
    name: "Brookfield Renewable Partners LP",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2005-11-15",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BEP-P-A",
    name: "Brookfield Renewable Partners LP 525 Class A Preferred Limited Partnership Units Series 17",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2020-02-20",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BEP-W",
    name: "Brookfield Renewable Partners L.P. Limited Partnership Units ExDistribution When Issued",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2020-07-24",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BEPC",
    name: "Brookfield Renewable Corporation - Class A - Class A (Sub Voting)",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2020-07-24",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BEPCW",
    name: "Brookfield Renewable Corporation Class A Subordinate When Issued",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2020-07-24",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BEPH",
    name: "Brookfield BRP Holdings (Canada) Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2021-04-16",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BEPI",
    name: "Brookfield BRP Holdings (Canada) Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2021-12-14",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BEPW",
    name: "Brookfield Renewable Partners L.P. Limited Partnership Units ExDistribution When Issued",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2020-07-24",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BERY",
    name: "Berry Global Group Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2012-10-04",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BERZ",
    name: "Bank of Montreal",
    exchange: "NYSE ARCA",
    assetType: "Stock",
    ipoDate: "2021-08-18",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BEST",
    name: "BEST Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2017-09-20",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BETZ",
    name: "Roundhill Sports Betting & iGaming ETF",
    exchange: "NYSE ARCA",
    assetType: "ETF",
    ipoDate: "2020-06-04",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BF-A",
    name: "Brown-Forman Corp - Class A",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1973-05-03",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BF-B",
    name: "Brown-Forman Corp - Class B",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1984-09-07",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFAC",
    name: "Battery Future Acquisition Corp - Class A",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2022-02-04",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFAC-U",
    name: "Battery Future Acquisition Corp - Units (1 Ord Class A & 1/2 War)",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2021-12-15",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFAC-WS",
    name: "Battery Future Acquisition Corp - Warrants (01/01/9999)",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2022-02-04",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFAM",
    name: "Bright Horizons Family Solutions Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2013-01-25",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFC",
    name: "Bank First Corp",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2002-01-29",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFEB",
    name: "Innovator U.S. Equity Buffer ETF - February",
    exchange: "BATS",
    assetType: "ETF",
    ipoDate: "2020-02-03",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFH",
    name: "Bread Financial Holdings Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2001-06-15",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFI",
    name: "BurgerFi International Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2018-03-26",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFIIW",
    name: "BurgerFi International Inc - Warrants (16/12/2025)",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2018-03-26",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFIN",
    name: "Bankfinancial Corp",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2005-06-28",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFIT",
    name: "Global X Health & Wellness ETF",
    exchange: "NASDAQ",
    assetType: "ETF",
    ipoDate: "2016-05-10",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFIX",
    name: "Build Bond Innovation ETF",
    exchange: "NYSE ARCA",
    assetType: "ETF",
    ipoDate: "2022-02-10",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFK",
    name: "BlackRock Municipal Income Trust",
    exchange: "NYSE",
    assetType: "ETF",
    ipoDate: "2001-07-27",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFLY",
    name: "Butterfly Network Inc - Class A",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2020-07-13",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFLY-WS",
    name: "Butterfly Network Inc - Warrants (27/05/2025)",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2020-07-13",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFO",
    name: "BlackRock Florida Municipal 2020 Term Tr",
    exchange: "NYSE",
    assetType: "ETF",
    ipoDate: "2003-09-29",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFOR",
    name: "Barron`s 400 ETF",
    exchange: "NYSE ARCA",
    assetType: "ETF",
    ipoDate: "2013-06-04",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFRI",
    name: "Biofrontera Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-10-29",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFRIW",
    name: "Biofrontera Inc - Warrants (27/10/2026)",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-10-29",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFS",
    name: "Saul Centers Inc",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "1993-08-19",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFS-P-D",
    name: "Saul Centers Inc Depositary Shares Series D",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2018-01-18",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFS-P-E",
    name: "Saul Centers Inc. PRF PERPETUAL USD Ser E Rep 1100th",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2019-09-11",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFST",
    name: "Business First Bancshares Inc",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2018-04-11",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFT-U",
    name: "Foley Trasimene Acquisition Corp II Units each consisting of one share of Class A common stock and onethird of one warrant",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2020-08-19",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFT-WS",
    name: "Foley Trasimene Acquisition Corp II Warrants each whole warrant exercisable for one share of Class A Common Stock at an exercise price of 11.50 per share",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2020-10-09",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFTR",
    name: "BlackRock Future Innovators ETF",
    exchange: "NYSE ARCA",
    assetType: "ETF",
    ipoDate: "2020-10-01",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFY",
    name: "BlackRock New York Municipal Income Trust II",
    exchange: "NYSE",
    assetType: "ETF",
    ipoDate: "2002-07-30",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BFZ",
    name: "BlackRock California Municipal Income Trust",
    exchange: "NYSE",
    assetType: "ETF",
    ipoDate: "2001-07-27",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BG",
    name: "Bunge Ltd",
    exchange: "NYSE",
    assetType: "Stock",
    ipoDate: "2001-08-02",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BGB",
    name: "Blackstone Strategic Credit Fund",
    exchange: "NYSE",
    assetType: "ETF",
    ipoDate: "2012-09-26",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BGCP",
    name: "BGC Partners Inc - Class A",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "1999-12-10",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BGFV",
    name: "Big 5 Sporting Goods Corp",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2002-09-17",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BGH",
    name: "Barings Global Short Duration High Yield Fund",
    exchange: "NYSE",
    assetType: "ETF",
    ipoDate: "2012-10-26",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BGI",
    name: "Birks Group Inc - Class A",
    exchange: "NYSE MKT",
    assetType: "Stock",
    ipoDate: "2005-11-15",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BGIO",
    name: "BlackRock 2022 Global Income Opportunity Trust",
    exchange: "NYSE",
    assetType: "ETF",
    ipoDate: "2017-02-24",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BGLD",
    name: "FT Cboe Vest Gold Strategy Quarterly Buffer ETF",
    exchange: "BATS",
    assetType: "ETF",
    ipoDate: "2021-01-21",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BGNE",
    name: "BeiGene Ltd",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2016-02-03",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BGR",
    name: "Blackrock Energy & Resources Trust",
    exchange: "NYSE",
    assetType: "ETF",
    ipoDate: "2004-12-23",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BGRN",
    name: "iShares USD Green Bond ETF",
    exchange: "NASDAQ",
    assetType: "ETF",
    ipoDate: "2018-11-27",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BGRY",
    name: "Berkshire Grey Inc - Class A",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-02-11",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "BGRYW",
    name: "Berkshire Grey Inc - Warrants (21/07/2026)",
    exchange: "NASDAQ",
    assetType: "Stock",
    ipoDate: "2021-02-12",
    delistingDate: null,
    status: "Active",
  },
  {
    symbol: "GREK",
    name: "Global X MSCI Greece ETF",
    exchange: "NYSE ARCA",
    assetType: "ETF",
    ipoDate: "2011-12-08",
    delistingDate: null,
    status: "Active",
  },
];
export { symbols };
